import { User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "u_1",
    name: "Anya Petrova",
    email: "anya.p@acme.io",
    initials: "AP",
    lastActive: "2024-03-10 14:30",
    roles: ["Admin"],
    extensions: ["cat_full", "con_audit", "con_dashboards"],
  },
  {
    id: "u_2",
    name: "Ben Miller",
    email: "ben.m@acme.io",
    initials: "BM",
    lastActive: "2024-03-09 09:15",
    roles: ["Editor", "Viewer"],
    extensions: ["cat_content", "cat_drafts", "con_media", "con_reports"],
  },
  {
    id: "u_3",
    name: "Chloe Lee",
    email: "chloe.l@acme.io",
    initials: "CL",
    lastActive: "2024-03-08 11:00",
    roles: ["Viewer"],
    extensions: ["cat_readonly"],
  },
  {
    id: "u_4",
    name: "David Rodriguez",
    email: "david.r@acme.io",
    initials: "DR",
    lastActive: "2024-03-07 18:45",
    roles: ["Admin", "Billing"],
    extensions: ["cat_user_mgmt", "cat_invoices", "con_subs"],
  },
  {
    id: "u_5",
    name: "Elena Morales",
    email: "elena.m@acme.io",
    initials: "EM",
    lastActive: "2024-03-06 16:00",
    roles: ["Editor"],
    extensions: ["cat_drafts"],
  },
  {
    id: "u_6",
    name: "Finn Powell",
    email: "finn.p@acme.io",
    initials: "FP",
    lastActive: "2024-03-05 10:10",
    roles: ["Support", "Viewer"],
    extensions: ["cat_tickets", "con_kb", "con_reports"],
  },
  {
    id: "u_7",
    name: "Grace Hill",
    email: "grace.h@acme.io",
    initials: "GH",
    lastActive: "2024-03-04 08:22",
    roles: ["Editor"],
    extensions: ["con_media"],
  },
];
